apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-system
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007 # Accessible via <Node-IP>:30007
